import { DEMO_PLANS, type DemoSlug } from '@logic-estancia/domain';

export type { DemoSlug } from '@logic-estancia/domain';
export type DemoLocale = 'es' | 'en';

export const demos = {
  nivora: {
    brand: 'Nivora One', kind: 'City apartment', plan: DEMO_PLANS.nivora, theme: 'nivora',
    es: { nav: ['El espacio','Guía local','Consulta demo'], eyebrow: 'Un lugar, una estancia', title: ['Vive la ciudad', 'desde dentro.'], intro: 'Un apartamento sereno para cuatro personas, pensado para caminar, cocinar despacio y volver sin prisa.', cta: 'Probar consulta', section: 'Todo lo que necesitas. Nada que estorbe.', body: 'Luz natural, materiales honestos y una guía local que empieza al salir por la puerta.', detail: ['4 huéspedes','2 dormitorios','1 propiedad'], panelTitle: 'Así llegaría una solicitud directa.', panelBody: 'Compara tres consultas ficticias y el contexto que podría reunir un email. La demostración no pide datos personales, no envía mensajes, no consulta inventario y no crea reservas.' },
    en: { nav: ['The space','Local guide','Demo enquiry'], eyebrow: 'One place, one stay', title: ['Live the city', 'from within.'], intro: 'A calm apartment for four, made for walking, slow cooking and returning without a rush.', cta: 'Try an enquiry', section: 'Everything you need. Nothing in the way.', body: 'Natural light, honest materials and a guide that starts at your doorstep.', detail: ['4 guests','2 bedrooms','1 property'], panelTitle: 'How a direct enquiry could arrive.', panelBody: 'Compare three fictitious enquiries and the context an email could contain. The demo asks for no personal data, sends no message, queries no inventory and creates no booking.' },
  },
  terrava: {
    brand: 'Terrava Collection', kind: 'Rural homes', plan: DEMO_PLANS.terrava, theme: 'terrava',
    es: { nav: ['Las casas','Experiencias','Panel demo'], eyebrow: 'Ocho casas · un paisaje', title: ['El tiempo cambia', 'cuando llegas.'], intro: 'Casas independientes reunidas por una misma manera de cuidar el territorio, el silencio y cada llegada.', cta: 'Ver panel demo', section: 'Ocho refugios. Una colección con criterio.', body: 'Cada casa conserva su carácter; el panel reúne una vista ficticia de disponibilidad, solicitudes y preparación.', detail: ['8 propiedades ficticias','Planning visual','Datos de ejemplo'], panelTitle: 'Panel visual del plan Gestión', panelBody: 'Explora un escenario ya preparado. No hay alta de propiedades, formularios operativos, mensajes, reservas ni sincronizaciones.' },
    en: { nav: ['The homes','Experiences','Demo panel'], eyebrow: 'Eight homes · one landscape', title: ['Time changes', 'when you arrive.'], intro: 'Independent homes brought together by one way of caring for land, quiet and every arrival.', cta: 'View demo panel', section: 'Eight retreats. One considered collection.', body: 'Every home keeps its character; the panel brings together a fictitious view of availability, enquiries and preparation.', detail: ['8 fictitious properties','Visual planning','Sample data'], panelTitle: 'Management plan visual panel', panelBody: 'Explore a prepared scenario. There is no property registration, operational form, messaging, booking or synchronisation.' },
  },
  aurem: {
    brand: 'Aurem Hotel', kind: 'Independent hotel', plan: DEMO_PLANS.aurem, theme: 'aurem',
    es: { nav: ['Habitaciones','Servicios','Panel demo'], eyebrow: '96 habitaciones · una atención precisa', title: ['Todo dispuesto', 'antes de llegar.'], intro: 'Un hotel contemporáneo donde la calma del huésped empieza con una operación que sabe qué toca ahora.', cta: 'Ver panel demo', section: 'La precisión también se siente.', body: 'Habitaciones silenciosas, servicio atento y un equipo que comparte un escenario operativo ficticio.', detail: ['96 habitaciones ficticias','Indicadores visuales','Vista multirrol'], panelTitle: 'Panel visual del plan Inteligente', panelBody: 'Consulta métricas y estados ya preparados. No hay checkout, pago, alta, reserva, envío ni conexión con sistemas reales.' },
    en: { nav: ['Rooms','Services','Demo panel'], eyebrow: '96 rooms · precise attention', title: ['Everything ready', 'before you arrive.'], intro: 'A contemporary hotel where guest calm starts with an operation that knows what needs attention now.', cta: 'View demo panel', section: 'Precision can be felt.', body: 'Quiet rooms, attentive service and a team sharing a fictitious operating scenario.', detail: ['96 fictitious rooms','Visual indicators','Multi-role view'], panelTitle: 'Intelligent plan visual panel', panelBody: 'Review prepared metrics and statuses. There is no checkout, payment, registration, booking, delivery or connection to live systems.' },
  },
} as const satisfies Record<DemoSlug, object>;
