export const content = {
  es: {
    nav: { levels: 'Planes', docs: 'Guías', contact: 'Ver mi punto de partida' },
    hero: {
      eyebrow: 'Web gestionada · reservas · operación',
      title: 'Web y gestor de estancias online,',
      accent: 'todo en un mismo proyecto.',
      body: 'Logic2B Estancias combina una web de marca con las capacidades de gestión que tu alojamiento necesita: solicitudes, reservas y trabajo diario, con un alcance definido y una implantación acompañada por nuestro equipo.',
      primary: 'Ver mi punto de partida', secondary: 'Explorar cómo funciona',
    },
    proof: { eyebrow: 'Una sola lectura del negocio', title: 'De la primera búsqueda al trabajo de cada día, sin perder el contexto.', body: 'Cada paso deja información útil para el siguiente. Logic2B Estancias ordena la experiencia digital y el flujo operativo por capacidades, sin convertir la implantación en un salto a ciegas.' },
    modes: {
      eyebrow: 'Una evolución con criterio', title: 'Mejora lo que importa hoy. Añade profundidad cuando la operación la pida.',
      mono: ['Protege la relación directa', 'Una presencia propia que explica por qué elegirte y convierte el interés en una conversación bajo tu marca.'],
      multi: ['Conserva el contexto', 'Consultas, reservas, llegadas y tareas comparten un recorrido reconocible para el equipo.'],
    },
    demos: { eyebrow: 'Míralo antes de decidir', title: 'Tres alojamientos ficticios. Tres problemas muy reconocibles.', open: 'Explorar caso ficticio' },
    levels: { eyebrow: 'Tres puntos de partida', title: 'No pagues complejidad antes de necesitarla.', note: 'El alcance se define por las capacidades que necesitas; el número de propiedades y unidades solo ayuda a dimensionar la implantación. No publicamos precios hasta contar con suficiente validación comercial.' },
    scope: {
      eyebrow: 'Una primera orientación, sin dejar tus datos',
      title: 'Dinos qué te frena. Te enseñamos por dónde empezar.',
      body: 'Ajusta tu escala y marca las capacidades que hoy tendrían impacto. La recomendación se calcula en tu navegador y el proyecto final se valida contigo.',
      properties: 'Propiedades', units: 'Unidades', needs: 'Qué necesitas poner en marcha',
      booking: 'Reservas, huéspedes y planning', automation: 'Mensajes, recordatorios y canales', operations: 'Equipo, mantenimiento y revenue',
      result: 'Recomendación inicial', use: 'Usar esta recomendación',
      plans: {
        basico: ['Básico', 'Tu marca gana una web gestionada, preparada para posicionar y abrir conversaciones comerciales directas.'],
        gestion: ['Gestión', 'Cada consulta y reserva encuentra su sitio junto a huéspedes, planning y preparación.'],
        inteligente: ['Inteligente', 'El equipo prioriza llegadas, mantenimiento e ingresos desde un centro operativo supervisado.'],
      },
      reasons: {
        single: 'Una sola unidad permite empezar sin complejidad operativa.',
        multi: 'El tamaño orienta el alcance, pero el plan se decide por capacidades.',
        booking: 'Has incluido reservas y trabajo diario.',
        automation: 'Has incluido automatización y canales.',
        operations: 'Has incluido coordinación avanzada de la operación.',
        scale: 'Revisaremos el volumen contigo para dimensionar implantación y soporte.',
      },
    },
    faq: {
      eyebrow: 'Antes de cambiar nada',
      title: 'Las preguntas que conviene resolver primero.',
      items: [
        ['¿Qué software necesito para gestionar un alojamiento turístico?', 'Depende de dónde se pierda valor. Si el problema es atraer y responder, puede bastar una web gestionada. Si ya coordinas reservas, huéspedes o equipo, conviene añadir Gestión o Inteligente. El diagnóstico lo decide por capacidades, no por tamaño.'],
        ['¿Puedo empezar solo con una web para recibir consultas directas?', 'Sí. Básico incluye web de marca, fundamentos SEO, hosting y mantenimiento sin obligarte a incorporar un dashboard. Las solicitudes por email se definen y validan dentro del alcance del proyecto.'],
        ['¿Logic2B Estancias sustituye a mi PMS, motor de reservas o channel manager?', 'No de forma automática. Revisamos qué herramientas deben mantenerse, migrarse o conectarse. Ninguna integración se da por hecha ni se activa fuera del alcance acordado.'],
        ['¿Tengo que configurar Logic2B Estancias por mi cuenta?', 'No. El equipo de Logic2B adapta y prepara por ti todo lo incluido en el alcance, prueba los casos importantes y te acompaña cuando ya está en marcha. Migraciones, integraciones y soporte extendido se acotan por separado.'],
        ['¿Qué partes de las demos funcionan de verdad?', 'La navegación y las superficies visuales funcionan con datos precargados. Pagos, reservas, canales, IA, mensajería y registros externos no se ejecutan; cada capacidad muestra su estado y lo necesario para activarla por proyecto.'],
        ['¿Cuánto cuesta implantar Logic2B Estancias?', 'Cada proyecto combina implantación y suscripción según capacidades, volumen, migraciones e integraciones. Los rangos públicos se incorporarán cuando exista suficiente validación comercial; mientras tanto, el diagnóstico sirve para acotar el punto de partida.'],
      ],
    },
    contact: { eyebrow: 'Una conversación útil, no una demo de ventas', title: 'Cuéntanos dónde se atasca hoy una reserva.', body: 'Una persona del equipo revisará tu contexto y te responderá con un punto de partida razonado. Sin precios inventados, integraciones dadas por hechas ni una propuesta más grande de lo necesario.', expectation: 'Revisaremos el contexto y responderemos en un día laborable.', submit: 'Quiero una recomendación', sending: 'Enviando…', ok: 'Solicitud entregada. Te responderemos en un día laborable.', error: 'No hemos podido entregarla. Prueba por WhatsApp o vuelve a intentarlo.', timeout: 'La conexión está tardando demasiado y no podemos confirmar la entrega. Vuelve a intentarlo: si la solicitud ya llegó, conservaremos una única referencia.', rateLimited: 'Has hecho varios intentos. Conservamos tus datos en el formulario; podrás volver a enviarlo en {seconds} s.', retrying: 'Reintentar en {seconds} s', receiptTitle: 'La conversación ya está en marcha.', receiptBody: 'Hemos recibido el contexto. Conserva la referencia por si necesitas retomar la solicitud con el equipo.', reference: 'Referencia', meetingAvailable: 'Si te resulta útil, también puedes elegir un horario.', meetingCta: 'Elegir horario', meetingFallback: 'No necesitas hacer nada más: te responderemos por email.' },
  },
  en: {
    nav: { levels: 'Plans', docs: 'Guides', contact: 'Find my starting point' },
    hero: {
      eyebrow: 'Managed website · bookings · operations',
      title: 'Website and online accommodation management,',
      accent: 'all in one project.',
      body: 'Logic2B Estancias combines a brand-led website with the management capabilities your accommodation business needs: enquiries, bookings and daily work, with a clear scope and an implementation supported by our team.',
      primary: 'Find my starting point', secondary: 'Explore how it works',
    },
    proof: { eyebrow: 'One view of the business', title: 'From the first search to each day’s work, without losing context.', body: 'Every step leaves useful information for the next. Logic2B Estancias organises the digital experience and operating flow by capability, without turning implementation into a leap in the dark.' },
    modes: {
      eyebrow: 'Progress with intent', title: 'Improve what matters today. Add depth when operations call for it.',
      mono: ['Protect the direct relationship', 'An owned presence that explains why guests should choose you and turns interest into a conversation under your brand.'],
      multi: ['Keep the context', 'Enquiries, bookings, arrivals and tasks share a journey the team can recognise.'],
    },
    demos: { eyebrow: 'See it before deciding', title: 'Three fictional stays. Three very familiar problems.', open: 'Explore fictional case' },
    levels: { eyebrow: 'Three starting points', title: 'Do not pay for complexity before you need it.', note: 'Capabilities determine the scope; property and unit count only help size implementation. Public pricing will follow sufficient commercial validation.' },
    scope: {
      eyebrow: 'Initial guidance, without sharing your details',
      title: 'Tell us what gets in the way. See where to start.',
      body: 'Adjust your scale and select the capabilities that would matter today. The recommendation is calculated in your browser and the final project is validated with you.',
      properties: 'Properties', units: 'Units', needs: 'What do you need to launch',
      booking: 'Bookings, guests and planning', automation: 'Messages, reminders and channels', operations: 'Teams, maintenance and revenue',
      result: 'Initial recommendation', use: 'Use this recommendation',
      plans: {
        basico: ['Basic', 'Your brand gains a managed website ready for search visibility and direct commercial conversations.'],
        gestion: ['Management', 'Every enquiry and booking finds its place alongside guests, planning and preparation.'],
        inteligente: ['Intelligent', 'The team prioritises arrivals, maintenance and revenue from a supervised operations centre.'],
      },
      reasons: {
        single: 'One unit can start without operational complexity.',
        multi: 'Size guides scope, while capabilities determine the plan.',
        booking: 'You included bookings and daily operations.',
        automation: 'You included automation and channels.',
        operations: 'You included advanced operations coordination.',
        scale: 'We review scale with you to size implementation and support.',
      },
    },
    faq: {
      eyebrow: 'Before changing anything',
      title: 'The questions worth answering first.',
      items: [
        ['What software do I need to manage an accommodation business?', 'It depends on where value is lost. If attraction and response are the problem, a managed website may be enough. If you already coordinate bookings, guests or teams, Management or Intelligent may fit. Capabilities—not size—drive the assessment.'],
        ['Can I start with a website for direct enquiries only?', 'Yes. Basic includes a brand website, SEO foundations, hosting and maintenance without forcing a workspace you do not need yet. Email enquiries are defined and validated within the project scope.'],
        ['Does Logic2B Estancias replace my PMS, booking engine or channel manager?', 'Not automatically. We review what should stay, migrate or connect. No integration is assumed or activated beyond the agreed scope.'],
        ['Do I have to configure Logic2B Estancias myself?', 'No. The Logic2B team adapts and prepares everything included in scope, tests important cases and stays with you after launch. Migrations, integrations and extended support are scoped separately.'],
        ['Which parts of the demos really work?', 'Navigation and visual surfaces work with preloaded data. Payments, bookings, channels, AI, messaging and external records are not executed; each capability shows its status and what a project would need to activate it.'],
        ['How much does Logic2B Estancias cost?', 'Each project combines implementation and subscription according to capabilities, scale, migrations and integrations. Public ranges will follow sufficient commercial validation; the assessment narrows the right starting point in the meantime.'],
      ],
    },
    contact: { eyebrow: 'A useful conversation, not a sales demo', title: 'Tell us where a booking gets stuck today.', body: 'A member of the team will review your context and reply with a reasoned starting point. No invented pricing, assumed integrations or a proposal larger than necessary.', expectation: 'We will review the context and reply within one business day.', submit: 'Get my recommendation', sending: 'Sending…', ok: 'Request delivered. We will reply within one business day.', error: 'We could not deliver it. Try WhatsApp or try again.', timeout: 'The connection is taking too long and we cannot confirm delivery. Try again: if the request already arrived, we will keep a single reference.', rateLimited: 'You have made several attempts. Your details remain in the form; you can send it again in {seconds}s.', retrying: 'Try again in {seconds}s', receiptTitle: 'The conversation is now under way.', receiptBody: 'We have received the context. Keep the reference in case you need to resume the request with the team.', reference: 'Reference', meetingAvailable: 'If useful, you can also choose a time.', meetingCta: 'Choose a time', meetingFallback: 'You do not need to do anything else: we will reply by email.' },
  },
} as const;
