export const content = {
  es: {
    nav: { levels: 'Planes', docs: 'Guías', contact: 'Ver mi punto de partida' },
    hero: {
      eyebrow: 'Web y gestión para alojamientos',
      lead: 'Gestiona',
      terms: ['reservas', 'estancias', 'tu equipo'],
      tail: 'sin complicarte.',
      label: 'Gestiona reservas, estancias y tu equipo sin complicarte.',
      body: 'Tu web, tus reservas y el día a día del alojamiento, en un mismo proyecto. Diseñado y preparado contigo. Desde 49 €/mes.',
      primary: 'Solicitar información', secondary: 'Ver el producto',
      shortcuts: ['Ver una web demo', 'Recorrer el flujo', 'Explorar gestor demo'],
      rail: 'Doce direcciones navegables',
      railTitle: 'Webs con carácter propio.',
      pause: 'Pausar movimiento', resume: 'Reanudar movimiento',
      note: 'Diseño propio, implantación acompañada y soporte cercano. Demos ficticias. Sin reservas, pagos ni mensajes reales.',
    },
    proof: { eyebrow: 'Una sola lectura del negocio', title: 'De la primera búsqueda al trabajo de cada día, sin complicarte.', body: 'Cada paso deja información útil para el siguiente. Logic2B Estancias ordena la experiencia digital y el flujo operativo por capacidades, sin convertir la implantación en un salto a ciegas.' },
    modes: {
      eyebrow: 'Una evolución con criterio', title: 'Mejora lo que importa hoy. Añade profundidad cuando la operación la pida.',
      mono: ['Protege la relación directa', 'Una presencia propia que explica por qué elegirte y convierte el interés en una conversación bajo tu marca.'],
      multi: ['Conserva el contexto', 'Consultas, reservas, llegadas y tareas comparten un recorrido reconocible para el equipo.'],
    },
    demos: { eyebrow: 'Míralo antes de decidir', title: 'Tres alojamientos ficticios. Tres problemas muy reconocibles.', open: 'Explorar caso ficticio' },
    levels: { eyebrow: 'Tres puntos de partida', title: 'Empieza con lo que necesitas. Crece a tu ritmo.', note: 'Precios orientativos, sin IVA. Implantación inicial aparte. El presupuesto final depende del alcance, las unidades y las conexiones necesarias.' },
    scope: {
      eyebrow: 'Una primera orientación, sin dejar tus datos',
      title: 'Dinos qué te frena. Te enseñamos por dónde empezar.',
      body: 'Ajusta tu escala y marca las capacidades que hoy tendrían impacto. La recomendación se calcula en tu navegador y el proyecto final se valida contigo.',
      properties: 'Propiedades', units: 'Unidades', needs: 'Qué necesitas poner en marcha',
      booking: 'Reservas, huéspedes y planning', automation: 'Mensajes, recordatorios y canales', operations: 'Equipo, mantenimiento y revenue',
      result: 'Recomendación inicial', use: 'Usar esta recomendación',
      plans: {
        basico: ['Básico', 'Tu marca gana una web gestionada, preparada para posicionar y abrir conversaciones comerciales directas.'],
        gestion: ['Gestión', 'Cada consulta y reserva encuentra su sitio junto a huéspedes, planning y preparación.'],
        inteligente: ['Inteligente', 'El equipo prioriza llegadas, mantenimiento e ingresos desde un centro operativo supervisado.'],
      },
      reasons: {
        single: 'Una sola unidad permite empezar sin complejidad operativa.',
        multi: 'El tamaño orienta el alcance, pero el plan se decide por capacidades.',
        booking: 'Has incluido reservas y trabajo diario.',
        automation: 'Has incluido automatización y canales.',
        operations: 'Has incluido coordinación avanzada de la operación.',
        scale: 'Revisaremos el volumen contigo para dimensionar implantación y soporte.',
      },
    },
    faq: {
      eyebrow: 'Antes de cambiar nada',
      title: 'Preguntas que nos hacen.',
      items: [
        ['¿Qué software necesito para gestionar un alojamiento turístico?', 'Depende de dónde se pierda valor. Si el problema es atraer y responder, puede bastar una web gestionada. Si ya coordinas reservas, huéspedes o equipo, conviene añadir Gestión o Inteligente. El diagnóstico lo decide por capacidades, no por tamaño.'],
        ['¿Puedo empezar solo con una web para recibir consultas directas?', 'Sí. Básico parte de una web con tu marca, SEO, hosting y mantenimiento. No necesitas un gestor. Acordamos contigo el contenido y cómo recibirás las consultas antes de publicar.'],
        ['¿Logic2B Estancias sustituye a mi PMS, motor de reservas o channel manager?', 'No de forma automática. Revisamos qué herramientas deben mantenerse, migrarse o conectarse. Ninguna integración se da por hecha ni se activa fuera del alcance acordado.'],
        ['¿Tengo que configurar Logic2B Estancias por mi cuenta?', 'No. El equipo de Logic2B adapta y prepara por ti todo lo incluido en el alcance, prueba los casos importantes y te acompaña cuando ya está en marcha. Migraciones, integraciones y soporte extendido se acotan por separado.'],
        ['¿Podéis adaptar un tema a mi alojamiento?', 'Sí. Partimos del estilo que elijas y lo adaptamos a tu marca, fotografías, espacios y contenido. Definimos contigo la estructura y los accesos al contacto.'],
        ['¿Cuánto cuesta implantar Logic2B Estancias?', 'Básico desde 49 €/mes, Gestión desde 149 €/mes e Inteligente desde 299 €/mes. Implantación desde 490 €, 990 € y 1.990 €, respectivamente. Son importes orientativos sin IVA; las integraciones y migraciones se presupuestan aparte.'],
      ],
    },
    contact: { eyebrow: 'Hablemos de tu alojamiento', title: 'Demos el siguiente paso.', body: 'Cuéntanos qué alojamiento tienes y qué quieres mejorar. Te ayudamos a elegir un plan y concretamos contigo el alcance y el presupuesto.', expectation: 'Revisaremos el contexto y responderemos en un día laborable.', submit: 'Solicitar información', sending: 'Enviando…', ok: 'Solicitud entregada. Te responderemos en un día laborable.', error: 'No hemos podido entregarla. Prueba por WhatsApp o vuelve a intentarlo.', timeout: 'La conexión está tardando demasiado y no podemos confirmar la entrega. Vuelve a intentarlo: si la solicitud ya llegó, conservaremos una única referencia.', rateLimited: 'Has hecho varios intentos. Conservamos tus datos en el formulario; podrás volver a enviarlo en {seconds} s.', retrying: 'Reintentar en {seconds} s', receiptTitle: 'La conversación ya está en marcha.', receiptBody: 'Hemos recibido el contexto. Conserva la referencia por si necesitas retomar la solicitud con el equipo.', reference: 'Referencia', meetingAvailable: 'Si te resulta útil, también puedes elegir un horario.', meetingCta: 'Elegir horario', meetingFallback: 'No necesitas hacer nada más: te responderemos por email.' },
  },
  en: {
    nav: { levels: 'Plans', docs: 'Guides', contact: 'Find my starting point' },
    hero: {
      eyebrow: 'Websites and management for accommodation',
      lead: 'Manage',
      terms: ['bookings', 'stays', 'your team'],
      tail: 'with less effort.',
      label: 'Manage bookings, stays and your team with less effort.',
      body: 'Your website, bookings and day-to-day operations in one project. Designed and set up with you. From €49/month.',
      primary: 'Request information', secondary: 'Explore the product',
      shortcuts: ['View a website demo', 'Follow the journey', 'Explore workspace demo'],
      rail: 'Twelve navigable directions',
      railTitle: 'Websites with their own character.',
      pause: 'Pause movement', resume: 'Resume movement',
      note: 'Your own design, guided implementation and personal support. Fictional demos. No live bookings, payments or messages.',
    },
    proof: { eyebrow: 'One view of the business', title: 'From the first search to each day’s work, with less effort.', body: 'Every step leaves useful information for the next. Logic2B Estancias organises the digital experience and operating flow by capability, without turning implementation into a leap in the dark.' },
    modes: {
      eyebrow: 'Progress with intent', title: 'Improve what matters today. Add depth when operations call for it.',
      mono: ['Protect the direct relationship', 'An owned presence that explains why guests should choose you and turns interest into a conversation under your brand.'],
      multi: ['Keep the context', 'Enquiries, bookings, arrivals and tasks share a journey the team can recognise.'],
    },
    demos: { eyebrow: 'See it before deciding', title: 'Three fictional stays. Three very familiar problems.', open: 'Explore fictional case' },
    levels: { eyebrow: 'Three starting points', title: 'Start with what you need. Grow at your pace.', note: 'Indicative prices, excluding VAT. Initial setup charged separately. Final pricing depends on scope, units and connections.' },
    scope: {
      eyebrow: 'Initial guidance, without sharing your details',
      title: 'Tell us what gets in the way. See where to start.',
      body: 'Adjust your scale and select the capabilities that would matter today. The recommendation is calculated in your browser and the final project is validated with you.',
      properties: 'Properties', units: 'Units', needs: 'What do you need to launch',
      booking: 'Bookings, guests and planning', automation: 'Messages, reminders and channels', operations: 'Teams, maintenance and revenue',
      result: 'Initial recommendation', use: 'Use this recommendation',
      plans: {
        basico: ['Basic', 'Your brand gains a managed website ready for search visibility and direct commercial conversations.'],
        gestion: ['Management', 'Every enquiry and booking finds its place alongside guests, planning and preparation.'],
        inteligente: ['Intelligent', 'The team prioritises arrivals, maintenance and revenue from a supervised operations centre.'],
      },
      reasons: {
        single: 'One unit can start without operational complexity.',
        multi: 'Size guides scope, while capabilities determine the plan.',
        booking: 'You included bookings and daily operations.',
        automation: 'You included automation and channels.',
        operations: 'You included advanced operations coordination.',
        scale: 'We review scale with you to size implementation and support.',
      },
    },
    faq: {
      eyebrow: 'Before changing anything',
      title: 'Frequently asked questions.',
      items: [
        ['What software do I need to manage an accommodation business?', 'It depends on where value is lost. If attraction and response are the problem, a managed website may be enough. If you already coordinate bookings, guests or teams, Management or Intelligent may fit. Capabilities—not size—drive the assessment.'],
        ['Can I start with a website for direct enquiries only?', 'Yes. Basic starts with your own website, SEO, hosting and maintenance. You do not need a workspace. We agree the content and how enquiries will reach you before launch.'],
        ['Does Logic2B Estancias replace my PMS, booking engine or channel manager?', 'Not automatically. We review what should stay, migrate or connect. No integration is assumed or activated beyond the agreed scope.'],
        ['Do I have to configure Logic2B Estancias myself?', 'No. The Logic2B team adapts and prepares everything included in scope, tests important cases and stays with you after launch. Migrations, integrations and extended support are scoped separately.'],
        ['Can you adapt a theme to my accommodation?', 'Yes. We start with your chosen style and adapt it to your brand, photography, spaces and content. Together we define the structure and contact routes.'],
        ['How much does Logic2B Estancias cost?', 'Basic from €49/month, Management from €149/month and Intelligent from €299/month. Initial setup from €490, €990 and €1,990 respectively. Indicative prices exclude VAT; integrations and migrations are quoted separately.'],
      ],
    },
    contact: { eyebrow: 'Let’s talk about your accommodation', title: 'Let’s take the next step.', body: 'Tell us about your accommodation and what you want to improve. We will help you choose a plan and agree the scope and budget with you.', expectation: 'We will review the context and reply within one business day.', submit: 'Request information', sending: 'Sending…', ok: 'Request delivered. We will reply within one business day.', error: 'We could not deliver it. Try WhatsApp or try again.', timeout: 'The connection is taking too long and we cannot confirm delivery. Try again: if the request already arrived, we will keep a single reference.', rateLimited: 'You have made several attempts. Your details remain in the form; you can send it again in {seconds}s.', retrying: 'Try again in {seconds}s', receiptTitle: 'The conversation is now under way.', receiptBody: 'We have received the context. Keep the reference in case you need to resume the request with the team.', reference: 'Reference', meetingAvailable: 'If useful, you can also choose a time.', meetingCta: 'Choose a time', meetingFallback: 'You do not need to do anything else: we will reply by email.' },
  },
} as const;
